version: 1.5.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
test:
  # only assemblies to test
  assemblies:
    only:
      - CommandLine.Tests.dll

configuration: Release
before_build:
- cmd: dotnet restore
build_script:
- cmd: build.cmd Release
after_test:
- choco install opencover.portable
- choco install dotnetcore-sdk
- choco install codecov
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:test -oldstyle
- codecov -f "results.xml" 
artifacts:
- path: '**\*.nupkg'
